tracing: Fix compile-time warnings caused by 72848b81b3dd
../kernel/trace/trace_events_synth.c:769:6: error: ISO C90 forbids mixing declarations and code [-Werror,-Wdeclaration-after-statement]
        int ret = trace_event_reg(call, type, data);
            ^